name: mqtt_plus
description: Build a convenient mqtt client, provide emitter and handler to write business code here.
version: 0.0.2
homepage:
repository: https://github.com/CalsRanna/mqtt_plus

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.0.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
